const canoeDesign = lazyCss.setStyleLib("canoeDesign", {
    canoeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton2: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton3: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton4: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton5: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },    canoeButton6: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton7: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton8: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton9: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton0: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton11: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton12: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton13: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton14: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton15: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton16: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton17: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton18: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton19: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButton20: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButtoqwen: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeBuqwrtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },    cqweanoeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canqweoeButrton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeBurqqwatton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButxczton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canasdoeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButfdgton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButtaaon: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeryButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButttrytron: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeuyiyuiButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeButyuiyton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoeBuyuihjtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },    canoyuikloeBut123ton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButto45n: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButazxcton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBfhutton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBuvtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBuzxctton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },canoyuikloeBuxcvtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBufghtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButtvbnvbnon: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButtoghjn: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButthuuton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButthhklon: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButkhukhuton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBkhukhuutton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBukuhkhutton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButkhukhuton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },canoyuiklkuhlhoeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBuhjkutton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButhjton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeButwqeqwton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBuqwrqwrtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBuqwrtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },canoyuikloeBuqwetton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuiklqwroeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuiklqwrqwroeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeqweqwrButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloawdwqeeButton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },
    canoyuikloeBudawdtton: {
        fontSize: 14,
        height: 40,
        width: 100,
        paddingTop: 0,
        paddingBottom: 0,
        paddingLeft: 5,
        paddingRight: 5,
        textAlign: "center",
        textDecoration: 'none',
        textTransform: 'uppercase',
        verticalAlign: 'middle',
        outline: 'none',
        userSelect: 'none',
        borderRadius: '#1E9FFF',
        backgroundColor: '#1E9FFF',
        WebkitTapHighlightColor: 'transparent',
        cursor: 'pointer',
        boxShadow: 'none',
        transition: 'all .3s ease-out',
        color: '#000',
        border: '#1e9fff 1px solid',
        _hover:{
            opacity: '0.8',
            backgroundColor: '#66ccff',
            filter: 'alpha(opacity: 80)',
            color: '#fff'
        }
    },







})
